### PR TITLE
bugfix. fix 'multi line confirmation' not display

### PR DESCRIPTION
**Pull request by muxueqz**

### CODE REVIEW

**Comment by dpgaspar** [comment]
Sorry for the delay, i'll check this ASAP.

**Comment by dpgaspar** [comment]
Sorry, could you give a more detailed explanation? I don't get any bug on asking for user confirmation on actions with multiple rows

**Comment by muxueqz** [comment]
Not is 'multiple rows',
is multiple line text.

2015-03-19 19:04 GMT+08:00 Daniel Vaz Gaspar <notifications@github.com>:

> Sorry, could you give a more detailed explanation? I don't get any bug on
> asking for user confirmation on actions with multiple rows
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dpgaspar/Flask-AppBuilder/pull/115#issuecomment-83507918>
> .
>



-- 
明源
http://muxueqz.gitcafe.com
Twitter: @muxueqz <https://twitter.com/muxueqz>

**Comment by dpgaspar** [comment]
I've reverted this pull, it uses javascript alert to display messages.

Please use a different approach (using modal) or open an issue.

**Comment by muxueqz** [comment]
Thx!
This is better

**Pull request merged**
