### PR TITLE
Shell command

### PR DESCRIPTION
**Pull request by lu-zero**
It mimics Flask-Script `shell` command.

### CODE REVIEW

**Comment by dpgaspar** [comment]
This looks great and it's a good idea also, but it will only work with Flask 1.0 (dev), this is not out yet.

I could merge it already, but it won't work for the majority, latest version is 0.10.1, and there is no **make_shell_context**. #138

**Comment by lu-zero** [comment]
Oh, right, I forgot about it. Another item that might be nice is integrate alembic like it is done in Flask-Migrate.

**Comment by dpgaspar** [comment]
That would be nice too, are you willing to submit a pull for it?

**Comment by lu-zero** [comment]
I'll try this week-end it isn't as simple as for the shell and I have quite a bit of work to do.

**Comment by dpgaspar** [comment]
@lu-zero, sorry closing this one. 

On the future fabmanager should be converted to the "new" flask shell.

Something like:

```
flask fab create-admin
....
```
or
```
flask fabmanager create-admin
....
```

**Comment by lu-zero** [comment]
It is fine, sadly I got way too busy with other tasks =/

**Pull request closed without merging**
