### PR TITLE
Support jinja2 StrictUndefined.

### PR DESCRIPTION
**Pull request by jmcarp**
So that apps using appbuilder can configure jinja to error on undefined variables, explicitly test whether template variable are defined rather than treating undefined as falsy.

### CODE REVIEW

**Comment by jmcarp** [comment]
@dpgaspar PTAL when you have time.

**Comment by feng-tao** [comment]
PTAL @mistercrunch , Max, I recall you are also a maintainer of the repo?

**Comment by jmcarp** [comment]
Ping @dpgaspar @mistercrunch

**Comment by feng-tao** [comment]
hey Max @mistercrunch , when you have time, could you take a look?

**Comment by jmcarp** [comment]
@mistercrunch: I only added `jinja2.StrictUndefined` in unit tests to verify that all template variables are defined, so users shouldn't be affected.

**Comment by jmcarp** [comment]
Ping @mistercrunch @dpgaspar when you have time.

**Pull request merged**
