### PR TITLE
MongoEngine improvements (ListField, custom search)

### PR DESCRIPTION
**Pull request by gdedabiou**

### CODE REVIEW

**Comment by mistercrunch** [comment]
Please rebase

**Comment by dpgaspar** [comment]
Hi @gdedabiou 

This looks like a very nice addition, I'll run some tests.

**Comment by dpgaspar** [comment]
Hi @gdedabiou 

When running the example:

```
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app import app
  File "/Users/daniel.gaspar/workspace/python/Flask-AppBuilder/examples/mongo_employees/app/__init__.py", line 12, in <module>
    from views import add_views
  File "/Users/daniel.gaspar/workspace/python/Flask-AppBuilder/examples/mongo_employees/app/views.py", line 16, in <module>
    class EmployeeView(ModelView):
  File "/Users/daniel.gaspar/workspace/python/Flask-AppBuilder/examples/mongo_employees/app/views.py", line 18, in EmployeeView
    print(datamodel.custom_search)
````

Please fix it, thks.

**Comment by dpgaspar** [comment]
Sorry for the delay, can you rebase it?

**Pull request closed without merging**
