### PR TITLE
refactor: OAuth - redirect direct to provider if just one provider exists

### PR DESCRIPTION
**Pull request by hyunjong-lee**
### Description

In AuthOAuthView, redirection is always needed.
If just one provider exists, users can go to the provider auth page directly without selection.
This PR refactor the above situation. 😄

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Is CRUD MVC related.
- [x] Is Auth, RBAC security related.
- [ ] Changes the security db schema.
- [ ] Introduces new feature
- [ ] Removes existing feature

### CODE REVIEW

**Review by dpgaspar — APPROVED** [review]

**Comment by dpgaspar** [comment]
@hyunjong-lee manually tested it, thank you for the improvement!

**Comment by melnikovmaksimv** [comment]
Hi.
Why this PR is missing in version  >= 3.4.0 ???
please add to version 3.4.0+

**Comment by manikandantk88** [comment]
Hi, 
This issue persists in superset version 3.1.1. Is anyone facing this issue? Do you have any workaround for this?

**Comment by oldchurch12** [comment]
Hi,

I also face the same issue. Any idea for a workaround ? We are using 3.1.0 and also 3.1.1

**Pull request merged**
