### PR TITLE
fix: load user info for okta

### PR DESCRIPTION
**Pull request by houqp**
### Description

Fix okta integration

### ADDITIONAL INFORMATION

- [x] Has associated issue: close https://github.com/dpgaspar/Flask-AppBuilder/issues/1577
- [ ] Is CRUD MVC related.
- [x] Is Auth, RBAC security related.
- [ ] Changes the security db schema.
- [ ] Introduces new feature
- [ ] Removes existing feature

### CODE REVIEW

**Comment by jonathonbattista** [comment]
What is the status on this?

**Comment by houqp** [comment]
waiting for project maintainer to approve and merge, but we are already running this in production :)

**Comment by jonathonbattista** [comment]
@houqp How did you go about packaging this?

**Comment by houqp** [comment]
pip install from my own git branch

**Comment by thesuperzapper** [comment]
@dpgaspar can you review this PR?

**Review by dpgaspar — APPROVED** [review]
Thank you for the fix!

**Comment by jonathonbattista** [comment]
When will a new release be cut?

**Comment by dpgaspar** [comment]
Next week

**Comment by thesuperzapper** [comment]
@houqp @dpgaspar do you think we also need to do this for "azure"?
https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/manager.py#L591-L609

**Comment by houqp** [comment]
I don't have the answer because I don't have the environment to test. I recommend giving it a try and file issue to report any bug you found.

**Comment by thesuperzapper** [comment]
Issue is I don't have any azure setup either!

Anyone who does, please comment!

**Comment by dpgaspar** [comment]
RC1 for 3.2.2 is out: https://pypi.org/project/Flask-AppBuilder/3.2.2rc1/

3.2.2 will be out today/tomorrow

**Comment by aliuyusuf003** [comment]
I am using azure oauth provider for superset on my localhost and I am getting this error "'Response' object has no attribute 'data'
" 
Can some one point me to the fix. Many thanks.

**Pull request merged**
