### PR TITLE
Fix: change the default email value for auth_remote_user in security manager

### PR DESCRIPTION
**Pull request by elukey**
The ab_user SQL table may have a unique constraint for the
'email' attribute, leading to failures while inserting data
for a new user registration. Changing the default to a
unique value should fix the problem.

Issue: #965

### CODE REVIEW

**Comment by dpgaspar** [comment]
Looks good and makes sense.

**Comment by elukey** [comment]
Any chance to get this merged and ready for the next release? :)

**Comment by dpgaspar** [comment]
Yes, a very high chance

**Comment by elukey** [comment]
@mistercrunch Do you think that this change is ok to be merged and imported in Superset?

**Comment by dpgaspar** [comment]
@elukey I'm planning to include this on 2.1.0 that will probably be out next week (mon, tues). But Superset has not released a FAB>2 yet, but it's already on master.

**Comment by elukey** [comment]
@dpgaspar thanks a lot!

**Pull request merged**
