### PR TITLE
[security] Fix: Fixed an AttributeError in manager.py when a permission is null.

### PR DESCRIPTION
**Pull request by richimus123**
Thank you for contributing to Flask-Appbuilder. 

For Fixes:

Please, prefix the title with "Fix, " and describe in detail what you're fixing and the steps required to reproduce the problem.

For new features:

Please, prefix the title with "New, " and describe this new feature in detail, remember to update documentation.

### CODE REVIEW

**Comment by richimus123** [comment]
Here is more context on what is happening, not sure yet why the permission is None, but this will harden against it somewhat.

`2019-12-11 16:08:17,878:ERROR:flask_appbuilder.base:'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/base.py", line 597, in _add_permission
    baseview.base_permissions, baseview.class_permission_name
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/security/manager.py", line 1188, in add_permissions_view
    if perm_view.permission.name not in base_permissions:
AttributeError: 'NoneType' object has no attribute 'name'
2019-12-11 16:08:17,880:ERROR:flask_appbuilder.base:Add Permission on View Error: 'NoneType' object has no attribute 'name'`

**Comment by dpgaspar** [comment]
Thank you,

Can you please fix flake8 on CI, line too long

**Comment by richimus123** [comment]
Fixed the long line, moved the NoneType check to its own line.

**Comment by dpgaspar** [comment]
Thank you @richimus123 !

**Pull request merged**
