### PR TITLE
fix: using base_filters with FilterEqualFunction not working for relation fields

### PR DESCRIPTION
**Pull request by ThomasP0815**
Description:
### issue #1745

ADDITIONAL INFORMATION

Has associated issue:
- [x] Is CRUD MVC related.
- [ ] Is Auth, RBAC security related.
- [ ] Changes the security db schema.
- [ ] Introduces new feature
- [ ] Removes existing feature

### CODE REVIEW

**Comment by ThomasP0815** [comment]
Why were all jobs canceled ?

**Comment by ThomasP0815** [comment]
image

**Comment by ThomasP0815** [comment]
grafik

**Comment by dpgaspar** [comment]
> grafik

right! I'll do the upgrade, I'll ping you back.

Thank you

**Comment by dpgaspar** [comment]
@ThomasP0815 got CI fixed here: https://github.com/dpgaspar/Flask-AppBuilder/pull/2013
please rebase!

**Review by dpgaspar — COMMENTED** [review]
can you add tests where it's clear what we are actually fixing?

**Comment by ThomasP0815** [comment]
@dpgaspar test added please have a look

**Review by dpgaspar — APPROVED** [review]

**Comment by dpgaspar** [comment]
LGTM, thank you once more

**Pull request merged**
