### PR TITLE
fix: Flask-OpenID dependency, install breaks

### PR DESCRIPTION
**Pull request by dpgaspar**
### Description

More context:

https://github.com/mitsuhiko/flask-openid/pull/60
https://github.com/apache/airflow/issues/18075

Using Airflow patched fork for now

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Is CRUD MVC related.
- [ ] Is Auth, RBAC security related.
- [ ] Changes the security db schema.
- [ ] Introduces new feature
- [ ] Removes existing feature

### CODE REVIEW

**Comment by potiuk** [comment]
Hey @dpgaspar  - I became maintainer and I relesaed https://pypi.org/project/Flask-OpenID/1.3.0/  which should install propely with the new setuptools. No need for  workarounds any more.

**Comment by reb00ter** [comment]
@potiuk requirements.txt contains `flask-openid==1.2.5` dependency. May be would be better to update it to 1.3.0?

**Comment by potiuk** [comment]
Absolutely. @dpgaspar -> I am going to delete the https://github.com/apache/airflow-flask-openid-fork repo and since 1.3.0 is out and "good", you should change to 1.3.0 :)

**Comment by dpgaspar** [comment]
@potiuk yep, just read all the "news" on Flask-OpenID. Going to close this one and update to requirements to 1.3.0, planning also to eventually move flask-openid to an optional dependency

**Comment by potiuk** [comment]
Oh yeah. Things were going pretty fast :). And that's cool that we got to fix it that fast!

**Pull request closed without merging**
