### PR TITLE
Support cas

### PR DESCRIPTION
**Pull request by LvSongping**

### CODE REVIEW

**Comment by MichaelPereira** [comment]
@LvSongping @zhwwu Could you add some tests if possible?

I'm not familiar with this authentication system but you can mock any external calls to return expect values just to make sure that rest of the logic is sound.

**Comment by zhwwu** [comment]
Thanks Michael - we are still testing out the changes, and will certainly add tests when we are ready to initiate pull request.


________________________________

**Comment by mistercrunch** [comment]
The build in master was broken for a while but has now been fixed. Please rebase or merge to pass the build.

**Comment by dpgaspar** [comment]
Hi @LvSongping and @zhwwu,

Thanks, could you please provide a description and documentation and provide some testes.

**Comment by dolfandringa** [comment]
I think we can close this pull request, right?

**Comment by zhwwu** [comment]
yes. please.


________________________________

**Comment by dolfandringa** [comment]
> Hi @LvSongping and @zhwwu,
> 
> Thanks, could you please provide a description and documentation and provide some **testes**.

Just before closing LMAO at the typo @dpgaspar

**Pull request closed without merging**
