### PR TITLE
Revert "Bump jQuery to 3.5 (#1351)"

### PR DESCRIPTION
**Pull request by dpgaspar**
This reverts commit 7e0cf446

Fixes tooltip not being rendered problem, and possibly #1362

### CODE REVIEW

**Comment by kaxil** [comment]
@dpgaspar Do you know if we can bump the jQuery version now ?

**Comment by HardikVijayPatel** [comment]
filed following issue for jQuery bump: https://github.com/dpgaspar/Flask-AppBuilder/issues/1671

**Comment by HardikVijayPatel** [comment]
@dpgaspar could you please update if this is safe to merge now?

**Comment by dpgaspar** [comment]
@HardikVijayPatel should have the same issue, this needs to be revisited and probably upgrade other dependencies also

**Comment by HardikVijayPatel** [comment]
@dpgaspar do we have a timeline on when this would be revisited?

**Pull request merged**
