### PR TITLE
Support cas

### PR DESCRIPTION
**Pull request by sumous**
New, Add support for cas 
issue is: #949 

1.support for cas 3.0
2.Add examples for cas in examples/cas

### CODE REVIEW

**Comment by sumous** [comment]
`email` attribute has a unique constraint, it should be `email=username + '@email.notfound'` 
Refer: #965

**Comment by dpgaspar** [comment]
Can you please add some tests?

**Comment by sumous** [comment]
> Can you please add some tests?

I am developing. Tests are added. 
I'll add docs later.

**Comment by sumous** [comment]
@dpgaspar all done.

**Comment by nakkasyamprasad** [comment]
Hello,

Have followed the provided configurations and able to route the Apache Superset URL (http) to CAS URL(https), but getting unauthorized  service exception in browser.

Because my CAS service is configured HTTPS with SSL enable (with certificates) and Superset is running without https/ssl, due to this getting unauthorized exception.

Could you please provide the steps to work superset with HTTPS/SSL.

Regards,
Syam

**Comment by ganesh8614** [comment]
> New, Add support for cas
> issue is: #949
> 
> 1.support for cas 3.0
> 2.Add examples for cas in examples/cas

Hello,

Have followed the provided configurations and able to route the Apache Superset URL (http) to CAS URL(https), but getting unauthorized service exception in browser.

Because my CAS service is configured HTTPS with SSL enable (with certificates) and Superset is running without https/ssl, due to this getting unauthorized exception.

Could you please provide the steps to work superset with HTTPS/SSL.

**Comment by nakkasyamprasad** [comment]
> 
> 
> New, Add support for cas
> issue is: #949
> 
> 1.support for cas 3.0
> 2.Add examples for cas in examples/cas

Hello,

After done the provided changes able to route the Apache Superset URL to CAS Login page, once CAS got authenticated getting below error in browser.

Could you please provide your inputs on the issue.

Browser URL: https://hostname:port/login/?ticket=ST-17-I2V2g5Qw1hQWYfCGW2YVEtz1voYcasHostName

500 - Internal Server Error
Stacktrace

        Traceback (most recent call last):
  File "/obi/ApacheSuperset/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/obi/ApacheSuperset/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/obi/ApacheSuperset/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/obi/ApacheSuperset/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/obi/ApacheSuperset/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/obi/ApacheSuperset/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/obi/ApacheSuperset/venv/lib/python3.6/site-packages/flask_appbuilder/security/views.py", line 776, in login
    userinfo = self.validateUser(session[cas_token_session_key])
  File "/obi/ApacheSuperset/venv/lib/python3.6/site-packages/flask_appbuilder/security/views.py", line 837, in validateUser
    attributes = xml_from_dict["cas:attributes"]
KeyError: 'cas:attributes'

Regards,
Syam

**Comment by nakkasyamprasad** [comment]
> 
> 
> > New, Add support for cas
> > issue is: #949
> > 1.support for cas 3.0
> > 2.Add examples for cas in examples/cas
> 
> Hello,
> 
> After done the provided changes able to route the Apache Superset URL to CAS Login page, once CAS got authenticated getting below error in browser.
> 
> Could you please provide your inputs on the issue.
> 
> Browser URL: https://hostname:port/login/?ticket=ST-17-I2V2g5Qw1hQWYfCGW2YVEtz1voYcasHostName
> 
> 500 - Internal Server Error
> Stacktrace
> 
> ```
>     Traceback (most recent call last):
> ```
> 
> File "/obi/ApacheSuperset/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
> response = self.full_dispatch_request()
> File "/obi/ApacheSuperset/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/obi/ApacheSuperset/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
> reraise(exc_type, exc_value, tb)
> File "/obi/ApacheSuperset/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
> raise value
> File "/obi/ApacheSuperset/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
> rv = self.dispatch_request()
> File "/obi/ApacheSuperset/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
> return self.view_functions[rule.endpoint](**req.view_args)
> File "/obi/ApacheSuperset/venv/lib/python3.6/site-packages/flask_appbuilder/security/views.py", line 776, in login
> userinfo = self.validateUser(session[cas_token_session_key])
> File "/obi/ApacheSuperset/venv/lib/python3.6/site-packages/flask_appbuilder/security/views.py", line 837, in validateUser
> attributes = xml_from_dict["cas:attributes"]
> KeyError: 'cas:attributes'
> 
> Regards,
> Syam

Any inputs on this issue will be appreciated.

Regards,
Syam

**Pull request closed without merging**
