### PR TITLE
Added support for managed LDAP servers.

### PR DESCRIPTION
**Pull request by mathausmendel**
Some LDAP server aren't enabled for anonymous bind and/or search. Added the option to use a manager account to query the server for the necessary data.

### CODE REVIEW

**Comment by dpgaspar** [comment]
Great!! let me run some tests on it.

**Comment by dpgaspar** [comment]
Thank you! can i ask you to update the docs also?

https://github.com/dpgaspar/Flask-AppBuilder/blob/master/docs/config.rst

**Comment by mathausmendel** [comment]
Sure! I'll do it ASAP.

**Comment by dpgaspar** [comment]
Are you still willing to update the docs?

**Pull request closed without merging**
