### PR TITLE
Fix, list view ordering problem of related model with dotted notation

### PR DESCRIPTION
**Pull request by deeagle001**
Fix for https://github.com/dpgaspar/Flask-AppBuilder/issues/884 issue.
Please read it for problem details.

In my fix, I used the `relationship` contained join statement (`primaryjoin`) for dotted notation query joins.

This deprecates the restriction to use the same field name for `relationship` as the related table's name, and allows the user to use more than one relation on the same model, whilst they can be used in dotted notation and be ordered.

`isouter` is needed for not to filter out the results in case the `relationship` is optional (`nullable`).
Wihtout it, the row number indicates the found results, but because of the join statement (inner), the list will not show the ones, where the `relationship` is null.

### CODE REVIEW

**Comment by dpgaspar** [comment]
Hi,

This looks good, can you rebase and update?

**Comment by deeagle001** [comment]
Sure. I will need three-way merge for this. The update seems not trivial for the first sight.
Thank you in advance for your patience!

**Comment by dpgaspar** [comment]
Nice! sorry for the delayed answer on this one

**Comment by deeagle001** [comment]
@dpgaspar I made the update and it seems travis accepts it.
Please review and accept the changes again.

**Comment by dpgaspar** [comment]
Ok, looks good

**Pull request merged**
