### PR TITLE
Dependency Bump - Previous 0.1.0 version pinned here had an invalid character in its name

### PR DESCRIPTION
**Pull request by tmswfrk**
and was not being built properly when built from source. Owner of module
created 0.1.1 version for me and I need this updated here for use upstream.

Thank you for contributing to Flask-Appbuilder. 

For Fixes:

Please, prefix the title with "Fix, " and describe in detail what you're fixing and the steps required to reproduce the problem.

For new features:

Please, prefix the title with "New, " and describe this new feature in detail, remember to update documentation.

### CODE REVIEW

**Comment by dpgaspar** [comment]
Strange that Pypi has 0.1.1 but on @betodealmeida 's : https://github.com/betodealmeida/python-rison/blob/master/prison/__version__.py
we still have 0.1.0

This probably should not be pinned on setup.py can you change it:
prison>=0.1.0<1.0.0

**Comment by betodealmeida** [comment]
@dpgaspar I published 0.1.1 yesterday because someone had a problem installing the `tgz`. For some reason the file in PyPI was called `prison-0.1.0-.tar.gz`, and I wasn't able to upload a file with the correct name because it said it already existed.

I just pushed my local repo, so if you check https://github.com/betodealmeida/python-rison/blob/master/prison/__version__.py it's now on 0.1.1.

**Comment by dpgaspar** [comment]
@betodealmeida, cool! thank you for your time. 

BTW prison is great! (this sounds strange!) 

:)

**Comment by tmswfrk** [comment]
Made the change as requested! Thank you.

**Pull request merged**
