### PR TITLE
Fixes #767: data_template of Select2AJAXWidget results in invalid HTML.

### LINKED ISSUE #767: data_template of Select2AJAXWidget results in invalid HTML
# Description
When using Select2AJAXWidget field widgets an HTML input tag is produced that contains a rogue double-quote (") character before the end of its opening tag and has a closing tag (`</input>`) which is invalid in the HTML doctype used by Flask Appbuilder.  This is then manipulated by JavaScript to produce a Select2 UI element.  Invalid HTML can render the Document Object Model invalid and lead to unpredictable behaviour when attempting to manipulate it.

# Proposed solution
The fix is a trivial one for which I shall submit a pull request referencing this issue.

Regards,
Nachtkinder

### PR DESCRIPTION
**Pull request by nachtkinder**

### CODE REVIEW

**Comment by nachtkinder** [comment]
Just for the record it appears to be the building of the CI environment for Python 3.5 that failed rather than my code changes.

Regards,
Nachtkinder

**Comment by dolfandringa** [comment]
It looks like @nachtkinder is right and the build is failing because Pillow couldn't be installed. We should re-run the tests. What is the best way to do that @dpgaspar? I am cloning his repos now to run his tests locally.

**Comment by dolfandringa** [comment]
I ran the tests locally for Python 3.5.2 and they run fine. So I think the merge request should be fine. @dpgaspar should we just approve and merge and wait for travis to kick off another test, or do you want to re-run this travis run first?

**Comment by dolfandringa** [comment]
Thanks @nachtkinder for the PR by the way

**Comment by nachtkinder** [comment]
@dolfandringa You're welcome.  I've been using FAB for a while now and it is nice to be able to give something back.  I have some PRs outstanding that contain some more significant changes.

Regards,
Nachtkinder

**Comment by dolfandringa** [comment]
> I have some PRs outstanding that contain some more significant changes.

I am slowly going through things at the moment. Just started to contribute. I will get to them at some point. If you feel there are any that are more important than other, let me know.

**Pull request merged**
