### PR TITLE
Bump jQuery to 3.5 (re: #1350)

### PR DESCRIPTION
**Pull request by ryw**
re: https://github.com/dpgaspar/Flask-AppBuilder/issues/1350

Not sure how to dev FAB locally, if you can give me a quick overview, or point me to a guide, I'm happy to test jQuery 3.5 and try to troubleshoot any issues that arise from bumping it.

### CODE REVIEW

**Comment by ryw** [comment]
Great - what do you think about merging and releasing 2.3.3?

**Comment by dpgaspar** [comment]
@ryw published 2.3.3rc1 on Pypi: https://pypi.org/project/Flask-AppBuilder/#history

Going to run tests on superset, should be easy to test it on Airflow also.
If all is good final version should be out this week

**Comment by dpgaspar** [comment]
rc1 had a bug not related to this, just pushed 2.3.3rc2

**Comment by dpgaspar** [comment]
Tested on superset and looks good, have had to time to test on Airflow?

This is ready to go
https://github.com/dpgaspar/Flask-AppBuilder/pull/1359

**Pull request merged**
