### PR TITLE
fix babel-extract command

### PR DESCRIPTION
**Pull request by RoganW**
support `-k gettext` parameter when extract translatable strings using `fabmanager babel-extract`.

### CODE REVIEW

**Comment by dpgaspar** [comment]
Sorry @RoganW,

I made a simple test and babel-extract included my test text in translations file (messages.po).

I added a simple gettext to the views.py

Could you clarify?

**Comment by RoganW** [comment]
@dpgaspar There was a problem when use `import gettext as __`
The test steps:
* add test code


* extract translatable strings by `fabmanager babel-extract`
`fabmanager babel-extract --target flask_appbuilder/translations/`

* open babel/messages.pot
There added 3 new translation records:


But there are no translation record for  `"Test gettext()"`

**Comment by dpgaspar** [comment]
Ok, thanks for the reply. I think that the best would be to add a new optional parameter that accepts multiple values, take a look at: http://click.pocoo.org/5/options/#tuples-as-multi-value-options

This way we could add whatever exception(s) one would like.

And then please add some docs to support it: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/docs/fabmanager.rst

Thank you!

**Comment by dpgaspar** [comment]
I would like to release new 1.9.1 tomorrow, will you be able to it until then?

**Comment by RoganW** [comment]
@dpgaspar Done.

**Comment by dpgaspar** [comment]
Great! thank you.

**Pull request merged**
