### PR TITLE
New, Fixes #1154 by adding LOGOUT_REDIRECT_URL

### LINKED ISSUE #1154: Make redirect after logout configurable
Hi all,

I think it would be really useful if the URL that Flask-Appbuilder redirects to after logout would be configurable - akin to Django's `LOGOUT_REDIRECT_URL` setting.

Right now, the user is redirected to the hompage:

[flask_appbuilder/security/views.py#L477](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/views.py#L477)
```
class AuthView(BaseView):
    route_base = ""
    login_template = ""
    invalid_login_message = lazy_gettext("Invalid login. Please try again.")
    title = lazy_gettext("Sign In")

    @expose("/login/", methods=["GET", "POST"])
    def login(self):
        pass

    @expose("/logout/")
    def logout(self):
        logout_user()
        return redirect(self.appbuilder.get_url_for_index)
```

This might not be what is desired though, maybe the user should see a "thank you and see you soon page" or something like that, and it can also lead to problems with setups that use oauth2 for authentication, because the user will be logged straight back in if the oauth2 provider is configured to allow login without a prompt. I think this is what happens in #1110
So I think having an option to configure where users are redirected to after logout would be really useful, e.g.

```
    return redirect(
        self.appbuilder.app.config.get(
            "LOGOUT_REDIRECT_URL", self.appbuilder.get_url_for_index
        )
    )
```

### PR DESCRIPTION
**Pull request by jeverling**
This pull request addresses #1154, by redirecting to `LOGOUT_REDIRECT_URL` in the *logout* view if `LOGOUT_REDIRECT_URL` is set in the config, falling back to `self.appbuilder.get_url_for_index`.
It also adds `LOGOUT_REDIRECT_URL` to the **Configuration keys** table in `docs/config.rst`, and adds a unit test.

### CODE REVIEW

**Comment by heul** [comment]
I know it's a stale and closed issue, but this seems like a simple enough addition. @dpgaspar , is there a chance of still merging it?

**Comment by kaojunsong** [comment]
@dpgaspar Hi Daniel, we also met the logout issue: https://github.com/dpgaspar/Flask-AppBuilder/issues/1110, and I think this MR can solve this problem, could you please help to merge the MR?

**Comment by donatas-jocas** [comment]
I've also run into same issue mentioned by @kaojunsong using Keycloak SSO provider for Airflow - have verified in my local env that suggested changes in this PR solves the problem. @dpgaspar would it be possible to merge this PR for the upcoming release, even though it is marked as stale and closed? Happy to contribute making this happen if you have suggestions

**Comment by jeverling** [comment]
I have merged latest master (`f0608fb`) into the branch to bring it up-to-date, but Github doesn't seem to pick that commit up automatically. Should I maybe create a new PR?

**Pull request closed without merging**
