### PR TITLE
fix: handle better missing Azure AD info when registering a new user

### PR DESCRIPTION
**Pull request by jonasjancarik**
### Description

Introduces logic for handling missing user meta information. Currently, if e.g. the first or last name are missing, registration fails with no clear indication of what went wrong.

This is based on a real issue we had with registering users with no first name or last name in their Azure AD user profile.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Is CRUD MVC related.
- [ ] Is Auth, RBAC security related.
- [ ] Changes the security db schema.
- [ ] Introduces new feature
- [ ] Removes existing feature

### CODE REVIEW

**Comment by dpgaspar** [comment]
@ jonasjancarik makes sense, but lint is failling

**Review by dpgaspar — CHANGES_REQUESTED** [review]
@jonasjancarik makes sense, but lint is failing

**Comment by jonasjancarik** [comment]
Yeah I'll try to get around to it and fix that.

I am also thinking that using just the first part of the email address (which the "upn" usually is - but it can also be set to something else) for username is not ideal - if you have people registering from different tenants, e.g. john@foo.com and john@bar.com, john wouldn't be a unique username.

So I will probably change that to using the whole email address (upn). (Currently the username will be based on the "oid" which is a long alphanumeric string - upn will be more readable.)

**Comment by dpgaspar** [comment]
probably related to: https://github.com/dpgaspar/Flask-AppBuilder/pull/1640

**Comment by thesuperzapper** [comment]
@jonasjancarik do you want to rebase and fix linting?

**Comment by thesuperzapper** [comment]
@jonasjancarik is this still something you are working on?

**Comment by jonasjancarik** [comment]
Hi, yes - sorry I haven't had a lot of time available for this. I was just checking what the linting issue was; I will try to rebase and push again

**Pull request closed without merging**
