### PR TITLE
Fix: Oauth security search is not sufficiently comprehensive

### PR DESCRIPTION
**Pull request by danrubenstein**
As described in #818, in the case where Google Oauth is used (and I think generally in Oauth all around), the current logic is to search for a username if the `username` key exists in the userinfo dictionary, and only if the `username` key does not exist is a search done with email. 

This fix searches for a user by username, and if the result of find_user from that search returns a false-y value, it then proceeds to search by email.

### CODE REVIEW

**Comment by danrubenstein** [comment]
Hi @dpgaspar @dolfandringa,

I'm having trouble requesting a review, but would you be willing to look at this and see if it fixes #818?Also do feel free to let me know if there's anything else you'd like from me here. 

Thanks for your time and consideration.

**Comment by mistercrunch** [comment]
LGTM

**Comment by danrubenstein** [comment]
I am happy to close this.

**Comment by holandes22** [comment]
@danrubenstein I'm curious how did you ended up solving this? I had to make a fork of FAB to use in our Airflow 1.10 deployment to make it work with google auth due to this

**Comment by steve12d** [comment]
Hi all, I also ran into the same issue and the [fix](https://github.com/danrubenstein/Flask-AppBuilder/commit/04f84b61bc170e12b8de6e5abef63de8fb644674?diff=split) used by @danrubenstein worked for me.

**Comment by danrubenstein** [comment]
@holandes22 - yeah, like you I think, I wanted to do RBAC with Airflow 1.10. The way we had solved with before trying to upgrade to Airflow 1.10 was with an Airflow Plugin that used a custom Flask BluePrint that would only interact with the creative / destructive paths.

This led to a very simple permission model that used the "owner" property of a DAG which would let the owner (as determined by name), plus some set of super users (as emails, although you could do this in another way) trigger, pause, etc a DAG, but everyone who could access the platform would have the equivalent of read-only access.

I might be able to dig up the source if you're interested - we're still using it instead of Flask-AppBuilder + RBAC, even after upgrading to 1.10.

**Comment by holandes22** [comment]
Thank you for the offering @danrubenstein! but it's fine, we ended up using your [fix](https://github.com/danrubenstein/Flask-AppBuilder/commit/04f84b61bc170e12b8de6e5abef63de8fb644674?diff=split) in our own fork

It works great, but I rather this be merged into upstream instead of having to fork the repo

**Comment by holandes22** [comment]
@dpgaspar any chance this can be re-opened and merged? We need to rely on a fork to keep using Airflow 1.10 with FAB

**Comment by kdwyer** [comment]
@dpgaspar it looks as if this issue was automatically closed after you reopened it.  It would be good to have this change merged, if you find it satisfactory.

**Comment by psheth-twist** [comment]
@dpgaspar We would love to upgrade to latest Airflow if this fix can be merged please :)

**Comment by danrubenstein** [comment]
I've lost the thread here - if someone else wants to pick it up, go for it.

**Pull request closed without merging**
