### PR TITLE
release: 3.1.1 RC3

### PR DESCRIPTION
**Pull request by dpgaspar**
### Description

3.1.1 RC2

```
Improvements and Bug fixes on 3.1.1
-----------------------------------

fix: MVC order by related column use alias (#1504) [Daniel Vaz Gaspar]
fix: remove unnecessary CSS class/styling from dropdowns (#1503) [Ryan Hamilton]
deps: constraint pre 1 packages following semver (#1502) [Daniel Vaz Gaspar]
fix: MVC order by on relation (#1500) [Daniel Vaz Gaspar]
docs: add github actions badge (#1501) [Daniel Vaz Gaspar]
fix: remove unnecessary classes from dropdowns (#1491) [Ryan Hamilton]
feat: migrate from travis to github actions (#1497) [Daniel Vaz Gaspar]
fix: lint (#1498) [Daniel Vaz Gaspar]
fix: Improve UX by moving drop-down caret within clickable target (#1492) [Ryan Hamilton]
style: use a clearer visual representation for "delete" actions (#1495) [Ryan Hamilton]
fix: "actions" on ModelViews with composite primary keys (#1493) [Ash Berlin-Taylor]
docs: migrate examples/quickhowto3 to version 3.x.x (#1488) [luizduma]
fix: REST API inner joins eager loading (#1486) [Daniel Vaz Gaspar]
```

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Is CRUD MVC related.
- [ ] Is Auth, RBAC security related.
- [ ] Changes the security db schema.
- [ ] Introduces new feature
- [ ] Removes existing feature

### CODE REVIEW

**Comment by kaxil** [comment]
Would appreciate if you can include https://github.com/dpgaspar/Flask-AppBuilder/pull/1493 in 3.1.1 too. It is currently breaking some views in Airflow Master

**Comment by dpgaspar** [comment]
@kaxil @ashb Just released RC2, if possible test it against Airflow.

**Comment by dpgaspar** [comment]
@kaxil @ashb pinging again released an RC3 to include:

```
fix: MVC order by related column use alias (#1504) [Daniel Vaz Gaspar]
fix: remove unnecessary CSS class/styling from dropdowns (#1503) [Ryan Hamilton]
```

**Comment by kaxil** [comment]
> @kaxil @ashb pinging again, released an RC3 to include:
> 
> ```
> fix: MVC order by related column use alias (#1504) [Daniel Vaz Gaspar]
> fix: remove unnecessary CSS class/styling from dropdowns (#1503) [Ryan Hamilton]
> ```

Thanks @dpgaspar, Testing it now, will keep you posted.

**Comment by kaxil** [comment]
Thanks I can confirm the fix works @dpgaspar

**Pull request closed without merging**
